# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audit_trail.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 1, "", "audit_trail.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11\x61udit_trail.proto\x12\naudittrail\x1a\x1cgoogle/protobuf/struct.proto"\xdb\x02\n\nAuditTrail\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x13\n\x0boccurred_on\x18\x02 \x01(\x03\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\x14\n\x0csub_category\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x06 \x01(\t\x12\x18\n\x10\x64\x65stination_name\x18\x07 \x01(\t\x12)\n\nscope_info\x18\x08 \x01(\x0b\x32\x15.audittrail.ScopeInfo\x12\x12\n\nip_address\x18\t \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\n \x01(\t\x12\x0e\n\x06source\x18\x0b \x01(\t\x12\x14\n\x0cservice_name\x18\x0c \x01(\t\x12+\n\x0blog_details\x18\r \x01(\x0b\x32\x16.audittrail.LogDetails\x12\x17\n\x0f\x61\x64\x64itional_info\x18\x0e \x01(\t"2\n\tScopeInfo\x12\x12\n\nscope_type\x18\x01 \x01(\t\x12\x11\n\tscope_ids\x18\x02 \x03(\t"\x9e\x01\n\nLogDetails\x12\x30\n\x0e\x63hanged_fields\x18\x01 \x03(\x0b\x32\x18.audittrail.ChangedField\x12/\n\rimpact_radius\x18\x02 \x03(\x0b\x32\x18.audittrail.ImpactRadius\x12-\n\x0c\x63hanged_json\x18\x03 \x01(\x0b\x32\x17.audittrail.ChangedJSON"^\n\x0c\x43hangedField\x12\x17\n\x0f\x66ield_label_key\x18\x01 \x01(\t\x12\x1a\n\x12\x62\x65\x66ore_transaction\x18\x02 \x03(\t\x12\x19\n\x11\x61\x66ter_transaction\x18\x03 \x03(\t"/\n\x0cImpactRadius\x12\x0f\n\x07\x63ontext\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\t"v\n\x0b\x43hangedJSON\x12\x33\n\x12\x62\x65\x66ore_transaction\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x32\n\x11\x61\x66ter_transaction\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Structb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "audit_trail_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_AUDITTRAIL"]._serialized_start = 64
    _globals["_AUDITTRAIL"]._serialized_end = 411
    _globals["_SCOPEINFO"]._serialized_start = 413
    _globals["_SCOPEINFO"]._serialized_end = 463
    _globals["_LOGDETAILS"]._serialized_start = 466
    _globals["_LOGDETAILS"]._serialized_end = 624
    _globals["_CHANGEDFIELD"]._serialized_start = 626
    _globals["_CHANGEDFIELD"]._serialized_end = 720
    _globals["_IMPACTRADIUS"]._serialized_start = 722
    _globals["_IMPACTRADIUS"]._serialized_end = 769
    _globals["_CHANGEDJSON"]._serialized_start = 771
    _globals["_CHANGEDJSON"]._serialized_end = 889
# @@protoc_insertion_point(module_scope)
