# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: location_analytics.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'location_analytics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18location_analytics.proto\x12,network_services.location_analytics.v1alpha1\"\x9a\x03\n\nClientRssi\x12\x17\n\nclient_mac\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tap_serial\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06\x61p_mac\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x16\n\tradio_mac\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x15\n\x08rssi_val\x18\x05 \x01(\x05H\x04\x88\x01\x01\x12\x17\n\nassociated\x18\x06 \x01(\x08H\x05\x88\x01\x01\x12\x18\n\x0b\x61ssoc_bssid\x18\x07 \x01(\tH\x06\x88\x01\x01\x12\x10\n\x03\x61ge\x18\x08 \x01(\rH\x07\x88\x01\x01\x12\x18\n\x0bnoise_floor\x18\t \x01(\rH\x08\x88\x01\x01\x12\x12\n\x05\x61p_ip\x18\n \x01(\tH\t\x88\x01\x01\x12\x14\n\x07\x61p_name\x18\x0b \x01(\tH\n\x88\x01\x01\x42\r\n\x0b_client_macB\x0c\n\n_ap_serialB\t\n\x07_ap_macB\x0c\n\n_radio_macB\x0b\n\t_rssi_valB\r\n\x0b_associatedB\x0e\n\x0c_assoc_bssidB\x06\n\x04_ageB\x0e\n\x0c_noise_floorB\x08\n\x06_ap_ipB\n\n\x08_ap_name\"\xc6\x02\n\tRssiEvent\x12\\\n\x10\x66irmware_version\x18\x01 \x01(\x0e\x32=.network_services.location_analytics.v1alpha1.FirmwareVersionH\x00\x88\x01\x01\x12O\n\x08raw_rssi\x18\x02 \x01(\x0b\x32\x38.network_services.location_analytics.v1alpha1.ClientRssiH\x01\x88\x01\x01\x12U\n\x0eproximity_rssi\x18\x03 \x01(\x0b\x32\x38.network_services.location_analytics.v1alpha1.ClientRssiH\x02\x88\x01\x01\x42\x13\n\x11_firmware_versionB\x0b\n\t_raw_rssiB\x11\n\x0f_proximity_rssi*~\n\x0f\x46irmwareVersion\x12 \n\x1c\x46IRMWARE_VERSION_UNSPECIFIED\x10\x00\x12#\n\x1f\x46IRMWARE_VERSION_CLIENT_8X_RSSI\x10\x01\x12$\n FIRMWARE_VERSION_CLIENT_10X_RSSI\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_analytics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FIRMWAREVERSION']._serialized_start=816
  _globals['_FIRMWAREVERSION']._serialized_end=942
  _globals['_CLIENTRSSI']._serialized_start=75
  _globals['_CLIENTRSSI']._serialized_end=485
  _globals['_RSSIEVENT']._serialized_start=488
  _globals['_RSSIEVENT']._serialized_end=814
# @@protoc_insertion_point(module_scope)
